### ISSUE TITLE
Adding a security disclaimer to the README?

### ISSUE THREAD

**Issue by lirantal** [azu/strict-eval#1]
Hi @azu,

I feel the _strict_ wording might confuse developers to think it is safe to put untrusted user input into this.

Given that many similar variations of `eval` libraries have been found to fail at mitigating code injection, and that if I understand correctly, `strict-eval` isn't presumed to mitigate that anyway and leaves this security concern to the user, perhaps worth to just add a security notice/disclaimer to the README?

**Comment by azu** [comment]
> I understand correctly, `strict-eval` isn't presumed to mitigate that anyway and leaves this security concern to the user,

Yes, You're correct.
This module is just `"use strict"` directive + `eval`.
There are no security feature.

> perhaps worth to just add a security notice/disclaimer to the README?

Welcome to PR :)

**Comment by lirantal** [comment]
Great, thanks, as expected :-)
